version: '3'

services:
  langchain-server:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8000"]
