version: '3'

services:
  langchain-server:
    build:
      context: .
    container_name: langchain-server
    ports:
      - "$WEBAPP_PORT:$WEBAPP_PORT"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["python", "serve.py"]
